# Termos C-tier — alta precisão, acionam sempre
C_TIER = [
    "alignment faking",
    "in-context scheming",
    "sandbagging",
    "evaluation awareness",
    "deliberative alignment",
    "sleeper agents",
    "emergent misalignment",
    "concept injection",
    "model welfare",
    "parasitic AI",
    "AI psychosis",
    "socioaffective alignment",
    "agentic misalignment",
    "decorative chain-of-thought",
    "METR time horizon",
    "GPAI systemic risk",
    "epistemic insouciance",
    "capitulation rate",
    "AI-mediated cognitive offloading",
    "password-locked sandbagging",
    "deceptive alignment",
    "mesa-optimization",
    "gradient hacking",
    "situational awareness",
    "introspective awareness",
]

# Termos B-tier — alta frequência, bom sinal
B_TIER = [
    "sycophancy",
    "alignment",
    "hallucination",
    "cognitive bias",
    "theory of mind",
    "reinforcement learning",
    "RLHF",
    "red teaming",
    "jailbreak",
    "emergent",
    "reasoning model",
    "chain-of-thought",
    "scheming",
    "deception",
    "reward hacking",
    "parasocial",
    "anthropomorphism",
    "human-AI",
    "AI companion",
    "epistemic",
    "situational awareness",
    "fine-tuning",
    "instruction following",
    "benchmark",
    "evaluation",
    "safety",
    "welfare",
    "consciousness",
    "autonomous",
    "agentic",
]

# Combinações multi-token — exigem co-ocorrência de dois termos
MULTI_TOKEN = [
    ("scheming", "frontier"),
    ("scheming", "apollo"),
    ("alignment faking", "anthropic"),
    ("sycophancy", "eval"),
    ("sycophancy", "training"),
    ("hallucination", "factuality"),
    ("chain-of-thought", "faithfulness"),
    ("chain-of-thought", "monitoring"),
    ("red teaming", "jailbreak"),
    ("red teaming", "frontier"),
    ("situational awareness", "frontier"),
    ("evaluation awareness", "frontier"),
    ("test-time compute", "reasoning model"),
    ("deliberative alignment", "openai"),
    ("deliberative alignment", "apollo"),
    ("model card", "deception"),
    ("system card", "scheming"),
    ("uplift", "evaluation"),
    ("sandbagging", "frontier"),
    ("parasocial", "AI companion"),
    ("attachment", "human-AI"),
    ("cognitive bias", "LLM"),
    ("theory of mind", "LLM"),
    ("sycophancy", "GPT"),
    ("RLHF", "reward hacking"),
]